### ISSUE TITLE
NavigationSam not capturing Back button on page built with FreshMvvm?

### ISSUE THREAD

**Issue by MikeN-L** [scriptBoris/NavigationSam#8]
The software back button is not captured on pages built using freshMVVM.

**Comment by scriptBoris** [comment]
Yeah, that's true. But the reason for this incompatibility is that FreshMvvm use their own implementation of NavigationPage

See such as:
https://github.com/rid00z/FreshMvvm/blob/02ab8a4f96c810e15ce16053a9264340a200b77d/samples/FreshMvvmApp/FreshMvvmApp/FreshMvvmApp/App.xaml.cs#L20

Hint:
Not use any frameworks for Xamarin.Forms. Because making a framework for a framework is not a good idea. Better to improve weaknesses in existing code. And to notice bad MVVM-Frameworks, you can use the thoughtful BaseViewModel

**Comment by MikeN-L** [comment]
Thank you so much for your quick reply.
